[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "project"
version = "0.1.0"
description = "My cool library"
requires-python = ">=3.8"


[tool.pytest.ini_options]
addopts = "-ra -s"
testpaths = ["tests"]
pythonpath = "src"


[tool.basedpyright]
pythonVersion = "3.12"
pythonPlatform = "Windows"
extraPaths = ["src"]


include = ["src"]


exclude = ["**/__pycache__", "**/migrations", "**/tests"]