[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "project"
version = "0.1.0"
description = "My cool library"
requires-python = ">=3.8"


[tool.pytest.ini_options]
addopts = "-ra -s"
testpaths = ["tests"]
pythonpath = "src"


[tool.basedpyright]
pythonVersion = "3.12"
pythonPlatform = "Windows"
extraPaths = ["src"]


include = ["src"]


exclude = ["**/__pycache__", "**/migrations", "**/tests"]


[tool.pyright]
# Основное
typeCheckingMode = "strict"
useLibraryCodeForTypes = true
pythonVersion = "3.12"
include = ["src", "tests"]
extraPaths = ["src"]
exclude = ["**/__pycache__"]

# Строгие правила (аналог basedpyright)
reportMissingTypeStubs = true
reportMissingImports = true
reportMissingModuleSource = true
reportIncompatibleMethodOverride = true
reportUnknownArgumentType = true
reportUnknownParameterType = true
reportUnknownVariableType = true
reportUnknownMemberType = true
reportPrivateUsage = true
reportUnnecessaryIsInstance = true
reportUnnecessaryCast = true
reportUnnecessaryTypeIgnoreComment = true
reportUninitializedInstanceVariable = true
reportUnusedCallResult = false
reportUnusedImport = false
reportUnusedVariable = false

# Поддержка тестов
# Позволяет игнорировать отсутсвие аннотаций у pytest фикстур, если надо
reportMissingParameterType = false
reportFunctionMemberAccess = false
reportPrivateImportUsage = false
