[project]
name = "shop-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "fastapi (>=0.116.1,<0.117.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "dotenv (>=0.9.9,<0.10.0)",
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^1.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
addopts = "-ra -s"
testpaths = ["tests"]
pythonpath = "src"
markers = [
    "integration: mark test as integration",
    "unit: mark test as unit"
]


[tool.basedpyright]
pythonVersion = "3.12"
pythonPlatform = "Windows"
extraPaths = ["src"]


include = ["src"]


exclude = ["**/__pycache__", "**/migrations", "**/tests"]


[tool.pyright]
# Основное
typeCheckingMode = "strict"
useLibraryCodeForTypes = true
pythonVersion = "3.12"
include = ["src", "tests"]
extraPaths = ["src"]
exclude = ["**/__pycache__"]

# Строгие правила (аналог basedpyright)
reportMissingTypeStubs = true
reportMissingImports = true
reportMissingModuleSource = true
reportIncompatibleMethodOverride = true
reportUnknownArgumentType = true
reportUnknownParameterType = true
reportUnknownVariableType = true
reportUnknownMemberType = true
reportPrivateUsage = true
reportUnnecessaryIsInstance = false
reportUnnecessaryCast = true
reportUnnecessaryTypeIgnoreComment = true
reportUninitializedInstanceVariable = true
reportUnusedCallResult = false
reportUnusedImport = false
reportUnusedVariable = false

# Поддержка тестов
# Позволяет игнорировать отсутсвие аннотаций у pytest фикстур, если надо
reportMissingParameterType = false
reportFunctionMemberAccess = false
reportPrivateImportUsage = false

