services:
  mysql:
    container_name: test-mysql
    image: mysql:8.0
    hostname: test-mysql
    ports:
      - "3306:3306"
    env_file:
      - ../environment/.env.test
    volumes:
      - test-mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  test-mysql-data: