services:
  mysql:
    container_name: test-mysql
    image: mysql:8.0
    hostname: test-mysql
    ports:
      - "3306:3306"
    env_file:
      - ../environment/.env.test
    volumes:
      - test-mysql-data:/var/lib/mysql
      - ../docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
  rabbitmq:
    container_name: test-rabbit
    image: rabbitmq:3-management
    hostname: test-rabbit
    ports:
      - "5672:5672"       # AMQP порт
      - "15672:15672"     # Веб-интерфейс
    env_file:
      - ../environment/.env.test
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
  maxwell:
    container_name: test-maxwell
    image: zendesk/maxwell
    hostname: test-maxwell
    env_file:
      - ../environment/.env.test
    volumes:
    - ../docker/maxwell/entrypoint.sh:/entrypoint.sh:ro
    - ../docker/maxwell/filter.js:/filter.js
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      - mysql
      - rabbitmq
    restart: unless-stopped
volumes:
  test-mysql-data:
  rabbitmq-data: